#!/bin/bash
# =============================================================================
# Convenience wrapper: submit paper-2 displacement scan as SLURM array.
# =============================================================================
# Usage:
#     bash scripts/phase1/submit_disp_scan.sh                # default %4
#     CONCURRENT=8 bash scripts/phase1/submit_disp_scan.sh   # 8 concurrent
#     INDICES=0-3   bash scripts/phase1/submit_disp_scan.sh  # only level-1 (4 cases)
#
# Pre-requisite: data generated by prepare_disp_scan_data.sh.
# =============================================================================

set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$WORK/projects/RAFT-DVC}"
cd "$PROJECT_DIR"

[ -f configs/phase1/case_matrix_disp_scan.yaml ] || { echo "MISSING case_matrix_disp_scan.yaml"; exit 1; }
[ -f scripts/phase1/slurm_disp_scan.sh ] || { echo "MISSING slurm_disp_scan.sh"; exit 1; }

# Activate env so case_helper.py can import yaml
# shellcheck disable=SC1091
if [ -z "${CONDA_PREFIX:-}" ] || [[ "$CONDA_PREFIX" != *"raft-dvc"* ]]; then
    if [ -f "$WORK/miniconda3/etc/profile.d/conda.sh" ]; then
        source "$WORK/miniconda3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        source "$HOME/miniconda3/etc/profile.d/conda.sh"
    fi
    conda activate "$WORK/envs/raft-dvc"
fi

CONCURRENT="${CONCURRENT:-4}"
INDICES="${INDICES:-}"

if [ -z "$INDICES" ]; then
    N_CASES=$(python scripts/phase1/case_helper.py \
        --matrix configs/phase1/case_matrix_disp_scan.yaml --count)
    LAST=$((N_CASES - 1))
    INDICES="0-${LAST}"
fi

ARRAY_SPEC="${INDICES}%${CONCURRENT}"

# Verify data exists for all cases we're about to submit
DATA_ROOT="$SCRATCH/raft-dvc/data_paper2_disp_scan"
MISSING_DATA=0
for IDX in $(seq $(echo "$INDICES" | tr '-' ' ' | head -1) $(echo "$INDICES" | tr '-' ' ' | tail -1)); do
    eval "$(python scripts/phase1/case_helper.py \
        --matrix configs/phase1/case_matrix_disp_scan.yaml --index "$IDX")"
    DISP_TAG="d$(printf '%g' "$INPUT_DISP_MAX")"
    EXPECTED="$DATA_ROOT/${DATA}_size64_${DISP_TAG}/train"
    if [ ! -d "$EXPECTED" ]; then
        echo "MISSING data: $EXPECTED (case idx $IDX = $NAME)"
        MISSING_DATA=$((MISSING_DATA + 1))
    fi
done

if [ "$MISSING_DATA" -gt 0 ]; then
    echo ""
    echo "ERROR: $MISSING_DATA cases missing pre-generated data."
    echo "Run first:  bash scripts/phase1/prepare_disp_scan_data.sh"
    exit 4
fi

echo "===================================================================="
echo "Paper-2 displacement scan submission"
echo "Project dir   : $PROJECT_DIR"
echo "Data root     : $DATA_ROOT"
echo "Array spec    : $ARRAY_SPEC"
echo "Cases preview :"
python scripts/phase1/case_helper.py \
    --matrix configs/phase1/case_matrix_disp_scan.yaml --list | head -25
echo "===================================================================="

read -rp "Proceed? [y/N] " ans
case "$ans" in
    y|Y) ;;
    *) echo "Aborted."; exit 0 ;;
esac

sbatch --array="${ARRAY_SPEC}" scripts/phase1/slurm_disp_scan.sh
echo "Submitted. Use 'squeue -u \$USER' to monitor."
