@echo off
REM =============================================================================
REM Paper-1 FIXED-sampler retrain, arm 3 of 3: 1/8 encoder @ 128^3
REM =============================================================================
REM Identical recipe to paper1_axis2_1_8_at128 (r8_medium_size128 [8,16],
REM batch 4 x accum 2, 300 epochs, pct-start 0.2, workers 4, seed 42); only
REM difference is the corr_sampler_version=2 code fix.
REM
REM Data lives on G: (C: lacks the ~100 GB) -- regenerated by
REM gen_fixed_1_8_data.bat.  Per project memory: 128^3 arm needs
REM FOR_DISABLE_CONSOLE_CTRL_HANDLER=1 and --no-persistent-workers.
REM =============================================================================

setlocal
cd /d %~dp0..\..\

set OUTPUT_ROOT=C:\Zixiang_local_data\raft-dvc\paper1
REM Data copied to C: NVMe (G: HDD copy kept as backup) -- 2026-07-13
set DATA_ROOT=C:\Zixiang_local_data\raft-dvc\data_paper1_axis2
set EXP_NAME=paper1_fixed_1_8_at128
set EXP_DIR=%OUTPUT_ROOT%\phase1\%EXP_NAME%

if not exist "%OUTPUT_ROOT%\phase1" mkdir "%OUTPUT_ROOT%\phase1"

set RESUME_ARG=
if exist "%EXP_DIR%\latest.pth" (
    echo [resume] Found %EXP_DIR%\latest.pth -- resuming
    set RESUME_ARG=--resume "%EXP_DIR%\latest.pth"
)

set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
set FOR_DISABLE_CONSOLE_CTRL_HANDLER=1

C:\Users\zt3323\.conda\envs\raft-dvc-2\python.exe scripts\phase1\train_phase1.py ^
    --model-config configs\models\raft_dvc_1_8_p2_r4.yaml ^
    --data-config  r8_medium_size128 ^
    --data-root    "%DATA_ROOT%" ^
    --output-root  "%OUTPUT_ROOT%" ^
    --experiment-name %EXP_NAME% ^
    --epochs 300 ^
    --batch-size 4 ^
    --grad-accum-steps 2 ^
    --max-lr 2.0e-4 ^
    --pct-start 0.2 ^
    --num-workers 4 ^
    --no-persistent-workers ^
    --seed 42 %RESUME_ARG%

endlocal
